{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "boat-backend.postgresqlName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "boat-backend.postgresqlName" . }}
    {{- include "boat-backend.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "boat-backend.postgresqlName" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "boat-backend.postgresqlName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "boat-backend.postgresqlName" . }}
        {{- include "boat-backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: PGDATA
              value: {{ .Values.postgresql.pgData }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.secretName }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - boat
                - -d
                - boat
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - boat
                - -d
                - boat
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  {{- if .Values.postgresql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.postgresql.persistence.accessModes | nindent 10 }}
        storageClassName: {{ .Values.postgresql.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
  {{- end }}
{{- end }}
