environment: dev

namespace:
  name: boatlab-dev

image:
  tag: sha-a5b7338

backend:
  replicas: 1

postgresql:
  persistence:
    size: 5Gi

ingress:
  hosts:
    - host: boatlab-dev.luigi99.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: boatlab-dev-tls
      hosts:
        - boatlab-dev.luigi99.cloud
