apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boat-backend-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: boat-backend
    app.kubernetes.io/part-of: boat
    app.kubernetes.io/environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/receipt-keeper/boat-gitops.git
    targetRevision: main
    path: charts/boat-backend
    helm:
      releaseName: boat-backend
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: boatlab-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
